import { Achievement, Milestone, WeeklyChallenge, SubscriptionPlan } from '@/types/gamification';

export const ACHIEVEMENTS: Achievement[] = [
  // Cultural Achievements
  {
    id: 'dilmun-scholar',
    nameAr: 'عالم دلمون',
    nameEn: 'Dilmun Scholar',
    description: 'أكمل 10 دروس في التاريخ البحريني',
    icon: '🏛️',
    category: 'cultural',
    requirement: { type: 'lessons', value: 10 },
    reward: { pearls: 50, badge: 'dilmun-scholar' },
    tier: 'gold',
  },
  {
    id: 'pearl-diver',
    nameAr: 'غواص اللؤلؤ',
    nameEn: 'Pearl Diver',
    description: 'اجمع 100 لؤلؤة',
    icon: '🤿',
    category: 'mastery',
    requirement: { type: 'pearls', value: 100 },
    reward: { pearls: 25, badge: 'pearl-diver' },
    tier: 'silver',
  },
  {
    id: 'bahrain-fort-guardian',
    nameAr: 'حارس قلعة البحرين',
    nameEn: 'Bahrain Fort Guardian',
    description: 'حافظ على سلسلة تعلم لمدة 7 أيام',
    icon: '🏰',
    category: 'consistency',
    requirement: { type: 'streak', value: 7 },
    reward: { pearls: 40, badge: 'fort-guardian' },
    tier: 'gold',
  },
  {
    id: 'tree-of-life-explorer',
    nameAr: 'مستكشف شجرة الحياة',
    nameEn: 'Tree of Life Explorer',
    description: 'استكشف جميع المواد الدراسية',
    icon: '🌳',
    category: 'exploration',
    requirement: { type: 'subjects', value: 6 },
    reward: { pearls: 60, badge: 'tree-explorer' },
    tier: 'pearl',
  },
  {
    id: 'speed-falcon',
    nameAr: 'صقر السرعة',
    nameEn: 'Speed Falcon',
    description: 'أكمل 5 دروس في أقل من 15 دقيقة لكل درس',
    icon: '🦅',
    category: 'speed',
    requirement: { type: 'lessons', value: 5 },
    reward: { pearls: 30, badge: 'speed-falcon' },
    tier: 'silver',
  },
  {
    id: 'excellence-champion',
    nameAr: 'بطل التميز',
    nameEn: 'Excellence Champion',
    description: 'احصل على 90% أو أكثر في 10 دروس',
    icon: '⭐',
    category: 'mastery',
    requirement: { type: 'score', value: 10 },
    reward: { pearls: 70, badge: 'excellence-champion' },
    tier: 'pearl',
  },
  {
    id: 'gulf-navigator',
    nameAr: 'ملاح الخليج',
    nameEn: 'Gulf Navigator',
    description: 'أكمل 25 درساً',
    icon: '⛵',
    category: 'mastery',
    requirement: { type: 'lessons', value: 25 },
    reward: { pearls: 50, badge: 'gulf-navigator' },
    tier: 'gold',
  },
  {
    id: 'manama-mathematician',
    nameAr: 'رياضياتي المنامة',
    nameEn: 'Manama Mathematician',
    description: 'أتقن جميع دروس الرياضيات للصف الثالث',
    icon: '🔢',
    category: 'mastery',
    requirement: { type: 'lessons', value: 15 },
    reward: { pearls: 80, badge: 'manama-math' },
    tier: 'pearl',
  },
  {
    id: 'arabic-master',
    nameAr: 'أستاذ اللغة العربية',
    nameEn: 'Arabic Master',
    description: 'أتقن جميع دروس اللغة العربية',
    icon: '📚',
    category: 'mastery',
    requirement: { type: 'lessons', value: 15 },
    reward: { pearls: 80, badge: 'arabic-master' },
    tier: 'pearl',
  },
  {
    id: 'science-pioneer',
    nameAr: 'رائد العلوم',
    nameEn: 'Science Pioneer',
    description: 'أكمل 20 تجربة علمية',
    icon: '🔬',
    category: 'exploration',
    requirement: { type: 'lessons', value: 20 },
    reward: { pearls: 55, badge: 'science-pioneer' },
    tier: 'gold',
  },
];

export const MILESTONES: Milestone[] = [
  {
    id: 'novice-learner',
    pearlTarget: 50,
    nameAr: 'المتعلم المبتدئ',
    nameEn: 'Novice Learner',
    reward: 'شارة البداية الرائعة',
    icon: '🌱',
    culturalStory: 'كل رحلة عظيمة تبدأ بخطوة واحدة، تماماً كما بدأت البحرين كجزيرة صغيرة وأصبحت مركزاً للحضارة',
  },
  {
    id: 'pearl-collector',
    pearlTarget: 100,
    nameAr: 'جامع اللؤلؤ',
    nameEn: 'Pearl Collector',
    reward: 'سلة اللؤلؤ الفضية',
    icon: '🐚',
    culturalStory: 'في الماضي، كان غواصو اللؤلؤ البحرينيون يجمعون اللؤلؤ من أعماق الخليج. أنت الآن تجمع لآلئ المعرفة!',
  },
  {
    id: 'dilmun-apprentice',
    pearlTarget: 250,
    nameAr: 'متدرب دلمون',
    nameEn: 'Dilmun Apprentice',
    reward: 'ختم حضارة دلمون',
    icon: '🏺',
    culturalStory: 'دلمون كانت مركزاً للتجارة والحضارة. تعلمك يشبه بناء حضارة من المعرفة',
  },
  {
    id: 'bahrain-scholar',
    pearlTarget: 500,
    nameAr: 'عالم البحرين',
    nameEn: 'Bahrain Scholar',
    reward: 'تاج المعرفة الذهبي',
    icon: '👑',
    culturalStory: 'علماء البحرين عبر التاريخ نشروا العلم والمعرفة. أنت الآن واحد منهم!',
  },
  {
    id: 'pearl-master',
    pearlTarget: 1000,
    nameAr: 'سيد اللؤلؤ',
    nameEn: 'Pearl Master',
    reward: 'لؤلؤة البحرين الكبرى',
    icon: '💎',
    culturalStory: 'اللؤلؤ البحريني كان الأجود في العالم. تميزك في التعلم يشبه اللؤلؤة النادرة والثمينة',
  },
  {
    id: 'legend-of-learning',
    pearlTarget: 2000,
    nameAr: 'أسطورة التعلم',
    nameEn: 'Legend of Learning',
    reward: 'لقب أسطورة البحرين',
    icon: '🌟',
    culturalStory: 'أنت الآن من الأساطير! مثل أساطير البحرين العظماء، ستُذكر بتميزك وإصرارك',
  },
];

export const WEEKLY_CHALLENGES_TEMPLATE: Omit<WeeklyChallenge, 'id' | 'weekStartDate' | 'progress' | 'completed' | 'expiresAt'>[] = [
  {
    nameAr: 'تحدي الأسبوع: سباق المنامة',
    nameEn: 'Week Challenge: Manama Race',
    description: 'أكمل 7 دروس هذا الأسبوع',
    icon: '🏃',
    goal: { type: 'lessons', target: 7 },
    reward: { pearls: 50, badge: 'weekly-warrior' },
  },
  {
    nameAr: 'تحدي التميز: صقر البحرين',
    nameEn: 'Excellence Challenge: Bahrain Falcon',
    description: 'احصل على 85% أو أكثر في 5 دروس',
    icon: '🦅',
    goal: { type: 'score', target: 85 },
    reward: { pearls: 60, badge: 'excellence-seeker' },
  },
  {
    nameAr: 'تحدي التنوع: مستكشف المواد',
    nameEn: 'Diversity Challenge: Subject Explorer',
    description: 'ادرس 4 مواد مختلفة هذا الأسبوع',
    icon: '🌈',
    goal: { type: 'subjects', target: 4 },
    reward: { pearls: 70, badge: 'diversity-champion' },
  },
  {
    nameAr: 'تحدي اللؤلؤ: غواص الأسبوع',
    nameEn: 'Pearl Challenge: Diver of the Week',
    description: 'اجمع 100 لؤلؤة هذا الأسبوع',
    icon: '🤿',
    goal: { type: 'pearls', target: 100 },
    reward: { pearls: 80, badge: 'pearl-hunter' },
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'basic-plan',
    nameAr: 'الباقة الأساسية',
    nameEn: 'Basic Plan',
    price: 10,
    currency: 'BHD',
    subjectsIncluded: 2,
    trialDays: 7,
    features: [
      'مادتان دراسيتان من اختيارك',
      'معلمون افتراضيون مدعومون بالذكاء الاصطناعي',
      'دروس تفاعلية مخصصة',
      'نظام المكافآت باللؤلؤ',
      'تقارير أسبوعية للوالدين',
      'الوصول عبر الويب والموبايل',
    ],
  },
  {
    id: 'premium-plan',
    nameAr: 'الباقة الشاملة',
    nameEn: 'Premium Plan',
    price: 30,
    currency: 'BHD',
    subjectsIncluded: 'all',
    popular: true,
    trialDays: 14,
    features: [
      'جميع المواد الدراسية (6 مواد)',
      'معلمون افتراضيون متقدمون',
      'دروس تكيفية في الوقت الفعلي',
      'نظام الإنجازات الكامل',
      'تحديات أسبوعية حصرية',
      'تقارير تفصيلية يومية',
      'الوصول عبر جميع الأجهزة',
      'أولوية في الدعم الفني',
      'محتوى ثقافي بحريني إضافي',
    ],
  },
];

export const TIER_COLORS = {
  bronze: '#CD7F32',
  silver: '#C0C0C0',
  gold: '#FFD700',
  pearl: '#E6E6FA',
};

export const TIER_GRADIENTS = {
  bronze: 'from-orange-400 to-orange-600',
  silver: 'from-gray-300 to-gray-500',
  gold: 'from-yellow-300 to-yellow-600',
  pearl: 'from-purple-200 to-pink-300',
};
